image: cypress/base:10
cypress-e2e:
    script:
        - npm install
        - npm run build
        - npm run test:e2e
    artifacts:
        paths:
            - cypress/videos/
            - cypress/screenshots/
            - /root/.npm/_logs/
        when: always
